### ISSUE TITLE
Grafana: broken pipe

### ISSUE THREAD

**Issue by ivanelgran23** [sipcapture/homer7-docker#110]
Hello! I installed the docker-composer **hom7-prom-all** image, but unfortunately grafana is constantly spamming with errors like these:
`grafana           | t=2021-12-15T18:27:24+0500 lvl=eror msg="Request error" logger=context userId=0 orgId=1 uname= error="Context.HTML:write tcp [::1]:3000->[::1]:43370: write: broken pipe"`
`grafana           | t=2021-12-15T18:27:25+0500 lvl=eror msg="Request error" logger=context userId=0 orgId=1 uname= error="Context.HTML:write tcp [::1]:3000->[::1]:43376: write: broken pipe"`
Please tell me how it can be fixed?

**Comment by talkyoo** [comment]
Same Error here - with hom7-influx-grafana.

**Comment by haup** [comment]
Hi, I am using the "hom7-prom-all" and changed a the definition of grafana quite a bit, there are no errors anymore. It seems that the healthcheck triggered the request error

 ```
grafana:
#    image: grafana/grafana:master
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - /data/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
#      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
    restart: unless-stopped
    ports:
      - "10.2.1.15:9030:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:3000/api/>
      interval: 1s
      timeout: 3s
      retries: 30
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: "50m"
```
