### ISSUE TITLE
incorrect mapping 9096:9060 in hom7-influx-grafana/docker-compose.yml

### ISSUE THREAD

**Issue by smith151** [sipcapture/homer7-docker#119]
Maybe this is the typing error in hom7-influx-grafana/docker-compose.yml:

```
  heplify-server:
    image: sipcapture/heplify-server
    container_name: heplify-server
    ports:
      - "9069:9060"
```

It's should be:

```
  heplify-server:
    image: sipcapture/heplify-server
    container_name: heplify-server
    ports:
      - "9069:9069"
```
