### ISSUE TITLE
Problem with docker-compose images

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/homer7-docker#40]
Hi

I am trying to install Homer7 via Docker and I am having problems running docker-compose up (with hom7-hep-influx)
This gives an error that says:

Pulling influxdb (influxdb:1.5-alpine)...
1.5-alpine: Pulling from library/influxdb
ERROR: no matching manifest for linux/386 in the manifest list entries

The server is an Ubuntu 18.04 and claims to have a linux/i686 architecture.

Any suggestions?
Thanks.

**Comment by lmangani** [comment]
Hello @mcebey1891 - I can't reproduce this. what platform and version of docker are you running?
You can try switching to the non-alpine container for influxdb and see if that makes a difference:
```
 influxdb:
    image: influxdb:1.5
    volumes:
      - ./influx:/var/lib/influxdb
    expose:
      - 8086
```
