### ISSUE TITLE
ERROR:  invalid input syntax for type json

### ISSUE THREAD

**Issue by husam212** [sipcapture/homer7-docker#66]
I keep getting the following  error:
```
postgres    | 2020-03-17 11:15:27.832 UTC [66] ERROR:  invalid input syntax for type json
postgres    | 2020-03-17 11:15:27.832 UTC [66] DETAIL:  Token "bmGhEfDoNeJ0m" is invalid.
postgres    | 2020-03-17 11:15:27.832 UTC [66] CONTEXT:  JSON data, line 1: ...","correlation_id":"M_eP0431313170w"bmGhEfDoNeJ0m...
postgres    | 	COPY hep_proto_1_call, line 80, column protocol_header: "{"protocolFamily":2,"protocol":17,"srcIp":"80.90.160.221","dstIp":"159.65.125.17","srcPort":5060,"ds..."
postgres    | 2020-03-17 11:15:27.832 UTC [66] STATEMENT:  COPY hep_proto_1_call(sid,create_date,protocol_header,data_header,raw) FROM STDIN
heplify     | 2020/03/17 11:15:27.833508 postgres.go:284: ERR pq: invalid input syntax for type json
heplify     | 2020/03/17 11:15:27.834590 postgres.go:292: ERR pq: Could not complete operation in a failed transaction
```

I'm using a simple Homer stack with [heplify](https://github.com/sipcapture/heplify) version 1.56, following is the compose:
```
version: "2.1"

services:
  homer:
    container_name: homer
    image: sipcapture/webapp:latest
    ports:
      - "80:80/tcp"
    environment:
      - "DB_HOST=postgres"
      - "DB_USER=root"
      - "DB_PASS=homerSeven"
    restart: unless-stopped
    depends_on:
      - heplify

  heplify:
    container_name: heplify
    image: sipcapture/heplify-server:latest
    ports:
      - "9060:9060/tcp"
      - "9060:9060/udp"
    command:
      - "./heplify-server"
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBDRIVER=postgres"
      - "HEPLIFYSERVER_DBADDR=postgres:5432"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS=homerSeven"
      - "HEPLIFYSERVER_DBDATATABLE=homer_data"
      - "HEPLIFYSERVER_DBCONFTABLE=homer_config"
      - "HEPLIFYSERVER_DBDROPDAYS=30"
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_DEDUP=true"
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: homerSeven
      POSTGRES_USER: root
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres-data:/var/lib/postgresql/data
```
