### ISSUE TITLE
[FR] Add pgadmin for Postgres administration

### ISSUE THREAD

**Issue by sido420** [sipcapture/homer7-docker#93]
Suggestion for docker compose file. We can add pgadmin for easier db administration for folks that are not familiar with Postgresql.

Here is something that worked for me.
```
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: <password here>
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_LISTEN_PORT: 5009
    expose:
      - 5009
    ports:
      - "5009:5009/tcp"
    restart: unless-stopped
#    volumes:
#      - "./pgadmin.json:/pgadmin4/servers.json:ro"
    depends_on:
      - db
```
It does not add the db instance to pgadmin automatically but that should be doable.
